# Generated by Django 4.2.10 on 2024-02-09 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_rename_reviews_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='categories',
            new_name='category',
        ),
    ]
