# Generated by Django 4.2.10 on 2024-02-26 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_review_course_alter_review_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='price',
            field=models.FloatField(),
        ),
    ]
