# Generated by Django 4.2.10 on 2024-02-28 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_courses_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='image',
            field=models.ImageField(default='defaultphoto.webp', upload_to='course-images'),
        ),
    ]
