# Generated by Django 4.2.10 on 2024-02-29 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_courses_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='image',
            field=models.ImageField(default='../static/course_images/default-course-img.jpeg', upload_to='course_images/'),
        ),
    ]
