# Generated by Django 4.2.10 on 2024-03-01 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_alter_courses_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rate',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
